export const SEARCH_TWEET_INPROGRESS = 'SEARCH_TWEET_INPROGRESS';
export const SEARCH_TWEET_SUCCESS = 'SEARCH_TWEET_SUCCESS';
export const LOAD_MORE_TWEET = 'LOAD_MORE_TWEET';
export const LOAD_MORE_TWEET_INPROGRESS = 'LOAD_MORE_TWEET_INPROGRESS';
export const LOAD_MORE_TWEET_SUCCESS = 'LOAD_MORE_TWEET_SUCCESS';
